Anshuman resort level writeup
CelesteClassic/newleste.p8 pull request #102
Opened 2024-05-11 11:25 UTC by AnshumanNeon

My writeup is complete. Actually it was complete long ago but i didn't open a pull request. You can merge it now. Tell me about the issues if there are any.

2024-05-11 19:13 UTC, Antibrain0 commented
This is looking pretty good! Some screenshots are out of order but that isn't really an issue. Some of the level appear to be cropped weirdly but that might just be my phone trying to "improve" readability.

As for the mess levels, I do like the idea of making them more linear, but as for removing wrapping back to the main room and things like that, that actually shouldn't be a big problem. We could just have that same level in the level metadata multiple times, with different level exits. (As in start exits to mess_1, end of mess_1 loads that same map data, but it exits to mess_2 in a different direction.)

Your writeup is great! Thank you for the help. I'll go ahead and review it, although I'll wait for cal to review to merge.

2024-05-11 19:14 UTC, Antibrain0 approved these changes
@Calverin , take a look at this when you can

2024-05-20 06:36 UTC, Antibrain0 approved these changes

2024-05-28 17:49 UTC, Calverin requested changes
Covered pretty much all needed ground with good level choices, nice job! I just made a few spelling/grammar suggestions and one requested inclusion in the Chapter Arc section

2024-05-28 17:49 UTC, Calverin commented on design/design_resort.md
> +- The chapter starts with introductory levels that introduce to main mechanics.
that introduce the player to the main mechanics.

2024-05-28 17:49 UTC, Calverin commented on design/design_resort.md
> +- Then the mess levels tests those mechanics.
The mess levels then test the player's knowledge of the mechanics.

2024-05-28 17:49 UTC, Calverin commented on design/design_resort.md
> +- The roof levels test the skill of player in those mechanics along with a boss fight.
The roof levels combine the previously introduced mechanics along with the added challenge of the Oshiro boss fight.

2024-05-28 17:49 UTC, Calverin commented on design/design_resort.md
> +As the mess levels are intertwined, they are beyond the limits of pico-8 and the space limitations of newleste.p8.
As the mess levels in the base game are intertwined, they would be beyond the limitations we have for newleste.p8 in their original form.

2024-05-28 17:49 UTC, Calverin commented on design/design_resort.md
> +That is why the mess levels are given linear progression in newleste.p8 and the specific levels and their orders are debatable and subject to change.
Instead, we will have the mess levels be linear as with the rest of the levels in the game.

2024-05-28 17:49 UTC, Calverin commented on design/design_resort.md
> +Keeping in mind these constraints should the levels be made.
Keep this all in mind if you plan on (re)creating levels with mess blocks

2024-05-28 17:49 UTC, Calverin commented on design/design_resort.md
> +If there are demands to change a level or add new levels or change the order of levels they are to be discussed in the official Celeste Classic discord server.
This isn't really a necessary line imo

2024-05-28 17:49 UTC, Calverin commented on design/design_resort.md
> +It should be said that first 4-6 levels are single screen ones and scrolling is gradually added later in the chapter. The most scrolling would be found in mess levels and roof levels.
"introduced" instead of "added"

2024-05-28 17:49 UTC, Calverin commented on design/design_resort.md
> +
Should probably discuss the Oshiro boss fight taking place in the roof levels here

2024-05-28 18:04 UTC, AnshumanNeon reviewed
lets go with this, i'll commit to revert back to make sure wrong changes are not done

2024-05-28 18:08 UTC, AnshumanNeon reviewed
review

2024-05-28 18:10 UTC, closed without merging